apis_ontology/urls.py
from apis_acdhch_default_settings.urls import urlpatterns
from django.urls import path, include
from rest_framework import routers

from apis_ontology.api_views import ListEntityRelations, SicprodModelViewSet, Network
from apis_ontology.views import ReferenceScanFail

urlpatterns += [path("apis/api/<contenttype:contenttype>/<int:pk>/relations", ListEntityRelations.as_view(), name="relationslist")]

# We override the generic ModelViewSet URIs using a custom ModelViewSet
# so we can add the faceting information to the `list` response
router = routers.DefaultRouter()
router.register(r"", SicprodModelViewSet, basename="genericmodelapi")
urlpatterns.insert(0, path("apis/api/<contenttype:contenttype>/", include(router.urls)))

urlpatterns += [path("apis/api/network", Network.as_view(), name="network")]

urlpatterns += [path("apis/failingreferences", ReferenceScanFail.as_view(), name="referencescanfail")]

urlpatterns += [path("", include("django_grouper.urls"))]

urlpatterns += [path("", include("apis_acdhch_django_auditlog.urls"))]

urlpatterns += [path("", include("django_interval.urls"))]

apis_ontology/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from apis_core.apis_entities.models import AbstractEntity
from .legacydatemixin import LegacyDateMixin
from apis_core.collections.models import SkosCollection, SkosCollectionContentObject
from apis_core.history.models import VersionMixin
from apis_core.apis_entities.abc import E53_Place
from apis_core.relations.models import Relation
from django_interval.fields import FuzzyDateParserField

from auditlog.registry import auditlog


class SicprodMixin(models.Model):
    """ A mixin providing generic fields and functionality for all Sicprod Models """
    review = review = models.BooleanField(default=False, help_text="Should be set to True, if the data record holds up quality standards.")
    status = models.CharField(max_length=100, blank=True)
    references = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    published = models.BooleanField(default=False)
    metadata = models.JSONField(null=True, blank=True, editable=False)

    class Meta:
        abstract = True

    def __str__(self):
        if self.name != "":
            return "{} (ID: {})".format(self.name, self.id)
        return "(ID: {})".format(self.id)

    def sicprod_collections(self):
        my_sccos = SkosCollection.objects.by_instance(instance=self)
        sicprod_c = SkosCollection.objects.get(name="sicprod")
        collection_c_t = ContentType.objects.get_for_model(SkosCollection)
        sccos = SkosCollectionContentObject.objects.filter(collection=sicprod_c, content_type=collection_c_t)
        return my_sccos.filter(id__in=[scco.content_object.id for scco in sccos])


class Person(VersionMixin, SicprodMixin, LegacyDateMixin, AbstractEntity):
    """
    Person, eine Subklasse von crm:E21_Person.
    """
    _default_search_fields = ["first_name", "name", "alternative_label"]
    first_name = models.CharField(max_length=1024, blank=True, null=True, verbose_name = "Vorname", help_text = "Vorname der Person.")
    name = models.CharField(max_length=255, verbose_name="Name", blank=True)
    GENDER_CHOICES = (("männlich", "männlich"), ("weiblich", "weiblich"), ("unbekannt", "unbekannt"), )
    gender = models.CharField(max_length=9, choices=GENDER_CHOICES, blank=True, verbose_name = "Geschlecht", help_text = "Geschlecht der Person.")
    alternative_label = models.TextField(blank=True, null=True, verbose_name = "Alternative Namen", help_text = "Feld um alternative Namen anzugeben.")

    class Meta:
        ordering = ["name", "first_name"]

    def __str__(self):
        return "{}, {} (ID: {})".format(self.name, self.first_name, self.id)


class Function(VersionMixin, SicprodMixin, LegacyDateMixin, AbstractEntity):
    """
    Eine Funktion kann von einer Person an einer Institution oder einem Hof ausgeübt werden kann.
    """
    _default_search_fields = ["name", "alternative_label"]
    name = models.CharField(max_length=255, verbose_name="Name", blank=True)
    alternative_label = models.TextField(blank=True, null=True, verbose_name = "Alternativer Name", help_text = "Andere Namen für die Funktion.")

    class Meta:
        ordering = ["name"]


class Place(VersionMixin, SicprodMixin, LegacyDateMixin, E53_Place, AbstractEntity):
    """
    Orte in SiCProD, Subklasse von crm:E53_Place.
    """
    _default_search_fields = ["label", "alternative_label"]
    alternative_label = models.TextField(blank=True, null=True, verbose_name = "Alternativer Name", help_text = "Alternativer Name für einen Ort.")
    TYPE_CHOICES = (("Stadt", "Stadt"), ("Dorf/Nachbarschaft/Gemein/Siedlung/Weiler", "Dorf/Nachbarschaft/Gemein/Siedlung/Weiler"), ("Burg/Schloss", "Burg/Schloss"), ("Land/Herrschaftskomplex", "Land/Herrschaftskomplex"), ("Landschaft/Region", "Landschaft/Region"), ("Lehen", "Lehen"), ("Haus/Hof", "Haus/Hof"), ("Gericht", "Gericht"), ("Kloster", "Kloster"), ("Gewässer", "Gewässer"), ("Grundherrschaft", "Grundherrschaft"), ("Hofmark", "Hofmark"), ("Tal", "Tal"), ("Berg", "Berg"), ("Bergrevier", "Bergrevier"), ("Pflege", "Pflege"), ("(Land-)Vogtei", "(Land-)Vogtei"), ("Propstei", "Propstei"), )
    type = models.CharField(max_length=41, choices=TYPE_CHOICES, blank=True, verbose_name = "Typ", help_text = "Art des Ortes.")

    class Meta:
        ordering = ["label"]


    def __str__(self):
        return self.label


class Institution(VersionMixin, SicprodMixin, LegacyDateMixin, AbstractEntity):
    """
    SiCProD Institution, Subklasse von crm:E74_Group. Wird für alle Institutionen benutzt die kein Hof sind
    """
    _default_search_fields = ["name", "alternative_label"]
    name = models.CharField(max_length=255, verbose_name="Name", blank=True)
    alternative_label = models.TextField(blank=True, null=True, verbose_name = "Alternativer Name", help_text = "Alternativer Name der Institution.")
    TYPE_CHOICES = (("Kanzlei", "Kanzlei"), ("Hofkapelle", "Hofkapelle"), ("Küche", "Küche"), ("(Dom-)Kapitel", "(Dom-)Kapitel"), ("Universität", "Universität"), ("Kloster", "Kloster"), ("Frauenzimmer", "Frauenzimmer"), ("Bistum", "Bistum"), ("Pfarrei", "Pfarrei"), )
    type = models.CharField(max_length=13, choices=TYPE_CHOICES, blank=True, verbose_name = "Typ", help_text = "Art der institution.")

    class Meta:
        ordering = ["name"]


class Event(VersionMixin, SicprodMixin, LegacyDateMixin, AbstractEntity):
    """
    SiCProD Ereignis, Subklasse von crm:E5_Event.
    """
    _default_search_fields = ["name", "alternative_label"]
    name = models.CharField(max_length=255, verbose_name="Name", blank=True)
    alternative_label = models.TextField(blank=True, null=True, verbose_name = "Alternativer Name", help_text = "Alternativer Name.")
    TYPE_CHOICES = (("Hochzeit", "Hochzeit"), ("Landtag", "Landtag"), ("Fest/Turnier", "Fest/Turnier"), ("Schlacht", "Schlacht"), ("Gesandtschaft/Reise", "Gesandtschaft/Reise"), ("Taufe", "Taufe"), ("Amtseinsetzung", "Amtseinsetzung"), ("Reichstag", "Reichstag"), )
    type = models.CharField(max_length=19, choices=TYPE_CHOICES, blank=True, verbose_name = "Typ", help_text = "Typ des Ereignisses.")

    class Meta:
        ordering = ["name"]


class Salary(VersionMixin, SicprodMixin, LegacyDateMixin, AbstractEntity):
    """
    Ein Gehalt ist die Menge an Geld die eine Person als Gegenleistung erhalten hat. Das Gehalt muss keine wiederkehrende Zahlung sein.
    """
    _default_search_fields = ["name"]
    name = models.CharField(max_length=255, verbose_name="Name", blank=True)
    TYP_CHOICES = (("Sold", "Sold"), ("Zehrung", "Zehrung"), ("Provision", "Provision"), ("Kredit", "Kredit"), ("Sonstiges", "Sonstiges"), ("Burghut", "Burghut"), ("Botenlohn", "Botenlohn"), )
    typ = models.CharField(max_length=9, choices=TYP_CHOICES, blank=True, verbose_name = "Typ", help_text = "Art des Gehalts.")
    REPETITIONTYPE_CHOICES = (("einfach", "einfach"), ("wiederholend", "wiederholend"), )
    repetitionType = models.CharField(max_length=12, choices=REPETITIONTYPE_CHOICES, blank=True, verbose_name = "Typ Wiederholungen", help_text = "Typ des Gehalts.")

    class Meta:
        ordering = ["name"]


auditlog.register(Person, serialize_data=True)
auditlog.register(Function, serialize_data=True)
auditlog.register(Place, serialize_data=True)
auditlog.register(Institution, serialize_data=True)
auditlog.register(Event, serialize_data=True)
auditlog.register(Salary, serialize_data=True)


class Bewohnt(VersionMixin, Relation):
    _legacy_property_id = 1
    subj_model = Person
    obj_model = Place

    legacy_relation_id = models.IntegerField(null=True, blank=True, editable=False)
    start = FuzzyDateParserField(null=True, blank=True)
    end = FuzzyDateParserField(null=True, blank=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["pk"]

    @classmethod
    def name(self) -> str:
        return "bewohnt"

    @classmethod
    def reverse_name(self) -> str:
        return "hat als Bewohner"


class Besitzt(VersionMixin, Relation):
    _legacy_property_id = 2
    subj_model = Person
    obj_model = Place

    legacy_relation_id = models.IntegerField(null=True, blank=True, editable=False)
    start = FuzzyDateParserField(null=True, blank=True)
    end = FuzzyDateParserField(null=True, blank=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["pk"]

    @classmethod
    def name(self) -> str:
        return "besitzt"

    @classmethod
    def reverse_name(self) -> str:
        return "ist im Besitz von"


class HatKorrespondenzMit(VersionMixin, Relation):
    _legacy_property_id = 3
    subj_model = Person
    obj_model = Person

    legacy_relation_id = models.IntegerField(null=True, blank=True, editable=False)
    start = FuzzyDateParserField(null=True, blank=True)
    end = FuzzyDateParserField(null=True, blank=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["pk"]

    @classmethod
    def name(self) -> str:
        return "hat Korrespondenz mit"

    @classmethod
    def reverse_name(self) -> str:
        return "hat Korrespondenz mit"


class HatFamilienbeziehungZu(VersionMixin, Relation):
    _legacy_property_id = 4
    subj_model = Person
    obj_model = Person

    legacy_relation_id = models.IntegerField(null=True, blank=True, editable=False)
    start = FuzzyDateParserField(null=True, blank=True)
    end = FuzzyDateParserField(null=True, blank=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["pk"]

    @classmethod
    def name(self) -> str:
        return "hat Familienbeziehung zu"

    @classmethod
    def reverse_name(self) -> str:
        return "hat Familienbeziehung zu"


class HatEheMit(VersionMixin, Relation):
    _legacy_property_id = 5
    subj_model = Person
    obj_model = Person

    legacy_relation_id = models.IntegerField(null=True, blank=True, editable=False)

apis_ontology/forms.py
from apis_core.generic.forms import GenericModelForm
from apis_ontology.models import Person


from apis_core.generic.forms.widgets import NewlineSeparatedListWidget


class SicprodMixinForm(GenericModelForm):

    class Meta(GenericModelForm.Meta):
        exclude = ["deprecated_name"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.fields["collections"].initial:
            self.fields["collections"].initial = [2, 5]

        if "alternative_label" in self.fields:
            self.fields["alternative_label"].widget = NewlineSeparatedListWidget(attrs={"class": "mb-1"})


class PersonForm(SicprodMixinForm):
    field_order = ["first_name", "name", "start_date_written", "end_date_written", "status", "collection", "gender", "alternative_label"]

    class Meta(SicprodMixinForm.Meta):
        model = Person
        exclude = ["published", "deprecated_name"]


class PlaceForm(SicprodMixinForm):
    field_order = ["label", "type", "latitude", "longitude", "status", "collection"]


class InstitutionForm(SicprodMixinForm):
    field_order = ["name", "start_date_written", "end_date_written", "kind", "status", "collection"]


class EventForm(SicprodMixinForm):
    field_order = ["name", "start_date_written", "end_date_written", "kind", "status", "collection"]


class FunctionForm(SicprodMixinForm):
    field_order = ["name", "start_date_written", "end_date_written", "kind", "status", "collection"]


class SalaryForm(SicprodMixinForm):
    field_order = ["name", "start_date_written", "end_date_written", "kind", "status", "collection"]

apis_ontology/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from apis_bibsonomy.models import Reference
from apis_ontology.serializers import iiif_titles, get_folio, normalize_title
import django_tables2 as tables
from django.utils.html import format_html


def scanfolderexists(ref):
    if "title" in ref.bibtexjson:
        return normalize_title(ref.bibtexjson["title"]) in iiif_titles()
    return False


def scanfolder(ref):
    normtitle = normalize_title(ref.bibtexjson["title"])
    return f"<a href='https://iiif.acdh-dev.oeaw.ac.at/images/sicprod/{normtitle}/'>{normtitle}/</a>"


class ReferenceFailTable(tables.Table):
    ref = tables.TemplateColumn('<a href="{% url "apis_bibsonomy:referenceupdate" record.id %}">{{ record }}</a>')
    folder = tables.Column(empty_values=())
    on = tables.Column(empty_values=())

    def render_on(self, record):
        try:
            obj = record.referenced_object
            rep = str(obj).replace("<", "").replace(">","")
            return format_html(f"<a href='{obj.get_absolute_url()}'>{rep}</a>")
        except Exception:
            return "Referenced object does not exist."

    def render_folder(self, record):
        return format_html(scanfolder(record))


class ReferenceScanFail(LoginRequiredMixin, tables.SingleTableView):
    template_name = "failingreferences.html"
    table_class = ReferenceFailTable

    def get_queryset(self, *args, **kwargs):
        refs = Reference.objects.all()
        refs = [ref for ref in refs if scanfolderexists(ref)]
        refs = [ref for ref in refs if get_folio(ref) is None]
        return refs

apis_ontology/templates/apis_entities/edit_generic.html
{% extends "apis_entities/edit_generic.html" %}
{% load bibsonomy_templatetags %}

{% block card-header-content %}
<h1>
{% link_to_reference_on obj=instance modal=True %}
  <a href="{{ instance.get_listview_url }}">
    <small>{{ entity_type }}s</small>
  </a>
  <strong>{{ instance }}</strong> <a href="{{ instance.get_absolute_url }}">
    <span class="material-symbols-outlined">visibility</span>
  </a>
  <a href="/entity/{{ instance.id }}">
    <span class="material-symbols-outlined">database</span>
  </a>
</h1>
{% endblock %}


{% block scripts %}
{{ block.super }}

{% if instance %}
<script type="text/javascript">
function GetFormAjax(FormName , ObjectID , ButtonText) {
    function add_form(data) {
	console.log("We are using the custom GetFormAjax");
        // update our tooltip content with our returned data and cache it
        $('#tab_'+data.tab).find('div:eq(1)').remove();
        $('#tab_'+data.tab).append(data.form);
        $('#form_PersonInstitutionForm div:first div:first select').focus();
        $('#tab_'+data.tab+" select.listselect2").each(function( index, element ){
            console.log($(this).data("autocompleteLightUrl"));
            $(this).select2({
                escapeMarkup: function(markup) {
                    return markup;
                },
                templateResult: function(data) {
                    return data.text;
                },
                templateSelection: function(data) {
                    return data.text;
                },
                ajax: {
                url: $(this).data("autocompleteLightUrl"),
                dataType: 'json'
                // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
                },
            })
        })            //$(".form.ajax_form").unbind()
        {% if apis_bibsonomy %}
        reinitialize_bibsonomy_tooltips();
	$('*[data-toggle="modal"]').each(function(){
	    htmx.process(this);
	});
        {% endif %}
    };
    if (!$.ApisForms) {
        $.ApisForms = {}
    };
    if (ObjectID === undefined) {
        if ($.ApisForms[FormName+'_'+'{{entity_type}}']) {
            var new_data = $.ApisForms[FormName+'_'+'{{entity_type}}']
            new_data.form = new_data.form.replace('##ENT_PK##', {{instance.pk}});
            add_form(new_data);
            return;
        };
    };
    if (ButtonText === undefined) {
        ButtonText = 'create/modify';
    };
    return $.ajax(
        {
            type: 'POST',
            url: '{% url 'apis:apis_relations:get_form_ajax' %}',
            beforeSend: function(request) {
                var csrftoken = getCookie('csrftoken');
                request.setRequestHeader("X-CSRFToken", csrftoken);
            },
            data: {
                'FormName':FormName,
                'SiteID':{{instance.pk}},
                'ObjectID':ObjectID,
                'ButtonText':ButtonText,
                'entity_type': '{{entity_type}}',
            },
            success: function(data) {
                add_form(data);
                if (!ObjectID) {
                    $.ApisForms[FormName+'_'+'{{entity_type}}'] = data;
                    $.ApisForms[FormName+'_'+'{{entity_type}}'].form = $.ApisForms[FormName+'_'+'{{entity_type}}'].form
                    .replace('/{{instance.pk}}/', '/##ENT_PK##/');
                };
            },
            error: function(error) {
                console.log(error)
            }
        }
    );
}
</script>
{% endif %}
<script>
var native_reinitialize_bibsonomy_tooltips = reinitialize_bibsonomy_tooltips;
reinitialize_bibsonomy_tooltips = function() {
  console.log("override reinitialize_bibsonomy_tooltips");
  native_reinitialize_bibsonomy_tooltips()
  notes = document.querySelectorAll("#id_notes");
  notes.forEach(notes => {
    notes.rows = 4;
  });
}
</script>
{% endblock scripts %}